### ISSUE TITLE
Will not compile.

### ISSUE THREAD

**Issue by mrmacman2u** [HOST-Oman/libraqm#188]
libraqm is failing to compile on Kubuntu 22.10 with supposed all deps satisfied. This is a fresh install of KUbuntu in an attempt to set up a Krita development box.

Error is attached

`~/libraqm/libraqm$ ninja -C ./build
ninja: Entering directory `./build'
[1/5] Compiling C object src/libraqm-test.a.p/raqm.c.o
FAILED: src/libraqm-test.a.p/raqm.c.o 
ccache cc -Isrc/libraqm-test.a.p -Isrc -I../src -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/local/include/harfbuzz -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O0 -g -fPIC -DRAQM_TESTING -DHAVE_CONFIG_H -MD -MQ src/libraqm-test.a.p/raqm.c.o -MF src/libraqm-test.a.p/raqm.c.o.d -o src/libraqm-test.a.p/raqm.c.o -c ../src/raqm.c
../src/raqm.c:39:10: fatal error: hb-ft.h: No such file or directory
   39 | #include <hb-ft.h>
      |          ^~~~~~~~~
compilation terminated.
[2/5] Compiling C object src/libraqm.so.0.10.0.p/raqm.c.o
FAILED: src/libraqm.so.0.10.0.p/raqm.c.o 
ccache cc -Isrc/libraqm.so.0.10.0.p -Isrc -I../src -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/local/include/harfbuzz -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O0 -g -fPIC -DHAVE_CONFIG_H -MD -MQ src/libraqm.so.0.10.0.p/raqm.c.o -MF src/libraqm.so.0.10.0.p/raqm.c.o.d -o src/libraqm.so.0.10.0.p/raqm.c.o -c ../src/raqm.c
../src/raqm.c:39:10: fatal error: hb-ft.h: No such file or directory
   39 | #include <hb-ft.h>
      |          ^~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.`

**Comment by khaledhosny** [comment]
looks like you built HarfBuzz yourself and you built it without FreeType support. If you are only building the dependencies for Raqm, you can probably skip this. Meson will download and build the dependencies for you if no suitable version is available on the system.
